### ISSUE TITLE
Fully opaque background

### ISSUE THREAD

**Issue by vanwagonet** [ollitapa/bitrise-step-stamp-appicon-with-version-number#1]
It looks like your code intends the caption background to be partially transparent `#0008`, but the way it is specified with extra quotes`"'#0008'"` makes it end up as straight black.

`convert: unrecognized color '#0008' @ warning/color.c/GetColorCompliance/1050.`

**Comment by ollitapa** [comment]
Good catch. Fixed it and also added customisation option here: 93d59a2f901d087549f98501fd36e5f96febaf0d I'll make a few more housekeeping updates and push an update to the main steplib later.

**Comment by ollitapa** [comment]
PR here: https://github.com/bitrise-io/bitrise-steplib/pull/1742
